# Generated by Django 3.1.2 on 2020-11-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('correo_electronico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_cliente',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(max_length=50)),
                ('via_principal', models.CharField(max_length=50)),
                ('numero_via_principal', models.CharField(max_length=10)),
                ('via_auxiliar', models.CharField(max_length=50)),
                ('numero_via_auxiliar', models.CharField(max_length=10)),
                ('inmueble', models.CharField(max_length=50)),
                ('interior', models.CharField(max_length=25)),
                ('numero', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('numero_lote', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('costo_por_porcion', models.IntegerField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_repartidor',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.administrador')),
                ('id_repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_empleado',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.administrador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_cliente',
            fields=[
                ('correo_electronico', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_administrador',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_inventario',
            fields=[
                ('numero_lote', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_en_carrito',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False)),
                ('unidades_por_producto', models.IntegerField()),
                ('cantidad_de_productos', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.usuario_empleado'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('num_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('precio_total', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('usuario_repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.usuario_repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_de_compras',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.cliente')),
                ('producto_en_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulza_tu_paseo_app.producto_en_carrito')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('id_producto', 'numero_lote')},
        ),
    ]
