# Generated by Django 3.1.2 on 2020-12-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endulzapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='usuario',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulzapp.empleado'),
        ),
        migrations.DeleteModel(
            name='Usuario_empleado',
        ),
    ]
