# Generated by Django 3.1.2 on 2020-12-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endulzapp', '0002_auto_20201203_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
