# Generated by Django 3.1.2 on 2020-12-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endulzapp', '0003_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endulzapp.administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repartidor',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repartidor',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario_repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endulzapp.repartidor'),
        ),
        migrations.DeleteModel(
            name='Usuario_repartidor',
        ),
    ]
